version: '2'
services:
    deepstream:
        image: cryptocracy/server
        ports:
            - "6020:6020"
    client:
        image: cryptocracy/client
        ports:
            - "80:80"
    wallets:
        image: cryptocracy/wallets
        ports:
            - "8888:8888"
        environment:
        - DEEPSTREAM_BCYPHERAPIKEY=
    accounts:
        image: cryptocracy/accounts
        ports:
            - "8999:8999"
    balances:
        image: cryptocracy/balances
    trade:
        image: cryptocracy/trade
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
    rethinkdb:
        image: rethinkdb
        ports:
            - "28015:28015"
    rethinkdb-search-provider:
        image: cryptocracy/rethinkdb-search-provider
        environment:
            - RETHINKDB_HOST=rethinkdb