version: '2'
services:
    deepstream:
        build: "."
        ports:
            - "6020:6020"
        volumes:
            - ./conf:/usr/local/deepstream/conf
            - ./var:/usr/local/deepstream/var
        depends_on:
            - redis
            - rethinkdb
    deepstream-search-provider:
        build: "./rethinkdb-search-provider"
        environment:
            - DEEPSTREAM_AUTH_PASSWORD=12345
            - RETHINKDB_HOST=rethinkdb
        depends_on:
            - deepstream
            - wallets
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
    rethinkdb:
        image: rethinkdb
        ports:
            - "28015:28015"
            - "8080:8080"
        volumes:
            - ./rethinkdb_data:/data/rethinkdb_data