##################################################################################
# Uncomment the appropriate volume below for your service and edit as necessary. #
##################################################################################

version: '2'
services:
    deepstream:
        extends:
            file: docker-compose-common.yml
            service: deepstream
        # volumes:
        #     - ./conf:/usr/local/deepstream/conf
        #     - ./var:/usr/local/deepstream/var
        #     - ./lib:/usr/local/deepstream/lib
    client:
        extends:
            file: docker-compose-common.yml
            service: client
        # volumes:
        # - ../client:/usr/local/client
    admin:
        image: cryptocracy/admin
        depends_on:
            - deepstream
        environment:
            - DEEPSTREAM_AUTH_PASSWORD=12345
        ports:
            - "88:88"
        environment:
            - PORT=88
        # volumes:
        #     - ../admin:/usr/local/admin
    wallets:
        extends:
            file: docker-compose-common.yml
            service: wallets
        environment:
            - DEEPSTREAM_AUTH_PASSWORD=12345
        # volumes:
        #     - ../wallets:/usr/local/wallets
    accounts:
        extends:
            file: docker-compose-common.yml
            service: accounts
        environment:
            - DEEPSTREAM_AUTH_PASSWORD=12345
        # volumes: 
        #     - ../accounts:/usr/local/accounts
    balances:
        extends:
            file: docker-compose-common.yml
            service: balances
        environment:
            - DEEPSTREAM_AUTH_PASSWORD=12345
        # volumes:
        # - ../balances:/usr/local/balances
    trade:
        extends:
            file: docker-compose-common.yml
            service: trade
        environment:
        - DEEPSTREAM_AUTH_PASSWORD=12345
        # volumes: 
        # - ../trade:/usr/local/trade
    redis:
        extends:
            file: docker-compose-common.yml
            service: redis
    rethinkdb:
        extends:
            file: docker-compose-common.yml
            service: rethinkdb
        image: rethinkdb
        ports:
            - "8080:8080"
        volumes:
            - ./rethinkdb_data:/data/rethinkdb_data
    rethinkdb-search-provider:
        extends:
            file: docker-compose-common.yml
            service: rethinkdb-search-provider
        environment:
            - DEEPSTREAM_AUTH_PASSWORD=12345