version: '2'
services:
    deepstream:
        image: cryptocracy/server
        ports:
            - "6020:6020"
        volumes:
            - ./conf:/usr/local/deepstream/conf
            - ./var:/usr/local/deepstream/var
        depends_on:
            - redis
            - rethinkdb
    wallets:
        image: cryptocracy/wallets
        ports:
            - "8888:8888"
        # environment:
        # - DEEPSTREAM_AUTH_PASSWORD=12345
        # - DEEPSTREAM_BCYPHERAPIKEY=APIKEYHERE
        depends_on:
            - deepstream
    balances:
        image: cryptocracy/balances
        # environment:
        # - DEEPSTREAM_AUTH_PASSWORD=12345
        # - DEEPSTREAM_BCYPHERAPIKEY=APIKEYHERE
        depends_on:
            - deepstream
    trade:
        image: cryptocracy/trade
        # environment:
        # - DEEPSTREAM_AUTH_PASSWORD=12345
        # - DEEPSTREAM_BCYPHERAPIKEY=APIKEYHERE
        depends_on:
            - deepstream
    deepstream-search-provider:
        image: cryptocracy/rethinkdb-search-provider
        environment:
            - DEEPSTREAM_AUTH_PASSWORD=12345
            - RETHINKDB_HOST=rethinkdb
        depends_on:
            - deepstream
            - wallets
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
    rethinkdb:
        image: rethinkdb
        ports:
            - "28015:28015"
            - "8080:8080"
        volumes:
            - ./rethinkdb_data:/data/rethinkdb_data