version: '2'
services:
    deepstream:
        image: cryptocracy/server
        ports:
            - "6020:6020"
        depends_on:
            - rethinkdb
            - redis
    client:
        image: cryptocracy/client
        ports:
            - "80:80"
        depends_on:
            - deepstream
            - wallets
            - accounts
            - balances
            - trade
    wallets:
        image: cryptocracy/wallets
        ports:
            - "8888:8888"
        environment:
        - DEEPSTREAM_BCYPHERAPIKEY=APIKEYHERE
        depends_on:
            - deepstream
    accounts:
        image: cryptocracy/accounts
        ports:
            - "8999:8999"
        depends_on:
            - deepstream
    balances:
        build: "../balances"
        depends_on:
            - deepstream
    trade:
        image: cryptocracy/trade
        depends_on:
            - deepstream
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
    rethinkdb:
        image: rethinkdb
        ports:
            - "28015:28015"
    rethinkdb-search-provider:
        image: cryptocracy/rethinkdb-search-provider
        environment:
            - RETHINKDB_HOST=rethinkdb
        depends_on:
            - deepstream