version: '2'
services:
    deepstream:
        image: cryptocracy/server
        ports:
            - "6020:6020"
        depends_on:
            - rethinkdb
            - redis
        # volumes:
        #     - ./conf:/usr/local/deepstream/conf
        #     - ./var:/usr/local/deepstream/var
        #     - ./lib:/usr/local/deepstream/lib
    client:
        image: cryptocracy/client
        ports:
            - "80:80"
        depends_on:
            - deepstream
            - accounts
            - wallets
            - balances
            - trade
        # volumes:
        #     - ../client:/usr/local/client
    wallets:
        image: cryptocracy/wallets
        ports:
            - "8888:8888"
        environment:
            - DEEPSTREAM_BCYPHERAPIKEY=
        depends_on:
            - deepstream
            - accounts
        # volumes:
        #     - ../wallets:/usr/local/wallets
    accounts:
        image: cryptocracy/accounts
        ports:
            - "8999:8999"
        environment:
            - DEEPSTREAM_AUTH_PASSWORD=12345
        depends_on:
            - deepstream
        # volumes: 
        #     - ../accounts:/usr/local/accounts
    balances:
        image: cryptocracy/balances
        environment:
            - DEEPSTREAM_AUTH_PASSWORD=12345
        depends_on:
            - deepstream
            - accounts
        # volumes:
        # - ../balances:/usr/local/balances
    trade:
        image: cryptocracy/trade
        environment:
            - DEEPSTREAM_AUTH_PASSWORD=12345
        depends_on:
            - deepstream
            - accounts
        # volumes:
        # - ../trade:/usr/local/trade
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
    rethinkdb:
        image: rethinkdb
        ports:
            - "28015:28015"
        volumes:
            - ./rethinkdb_data:/data/rethinkdb_data
    rethinkdb-search-provider:
        image: cryptocracy/rethinkdb-search-provider
        environment:
            - RETHINKDB_HOST=rethinkdb
            - DEEPSTREAM_AUTH_PASSWORD=12345
        depends_on:
            - deepstream
            - accounts